version: "3"

services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: transaction-builder-service-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}
